# API settings
api_endpoint: 'http://localhost:8080/api/v1/data/twitter/tweets/recent'
headers:
  accept: 'application/json'
  Content-Type: 'application/json'
request_timeout: 120

# Query settings
query: '(#memecoin)'
tweets_per_request: 200

# Date settings
start_date: '2024-08-01'
end_date: '2024-08-08'
days_per_iteration: 1

# File settings
data_directory: 'data'

# Timing settings
retry_delay: 960  # 16 minutes in seconds
request_delay: 15  # 15 seconds between requests
max_retries: 3

# Logging settings
log_level: 'INFO'
log_format: '%(asctime)s - %(levelname)s - %(message)s'