name: awesome-masa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.0
  - pip
  - requests
  - python-dotenv
  - pandas
  - feedparser
  - pip:
    - -r requirements.txt
    - assemblyai
    - pytube
    - TikTokApi
    - torch
    - transformers
    - numpy
    - pinecone
    - streamlit
    - ollama
    - colorlog