name: awesome-masa
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - streamlit
  - requests
  - python-dotenv
  - feedparser
  - pip:
    - -r requirements.txt