# API settings
api_endpoint: 'http://localhost:8080/api/v1/data/twitter/tweets/recent'
headers:
  accept: 'application/json'
  Content-Type: 'application/json'

# Query settings
query: '(#memecoin)'
tweets_per_request: 10

# Add start_date and end_date
start_date: '2024-08-01'
end_date: '2024-08-12'
days_per_iteration: 1

# File settings
data_directory: 'data'

# Timing settings
retry_delay: 960 
request_delay: 15
max_retries: 3 
request_timeout: 30

# Logging settings
log_level: 'INFO'
log_format: '%(asctime)s - %(levelname)s - %(message)s'