# API settings
api_endpoint: 'http://52.6.77.89:8080/api/v1/data/twitter/tweets/recent'
headers:
  accept: 'application/json'
  Content-Type: 'application/json'

# Query settings
query: '(from:bondexapp)'
tweets_per_request: 25

# Add start_date and end_date
start_date: '2024-01-01'
end_date: '2024-09-05'
days_per_iteration: 1

# File settings
data_directory: 'data'

# Timing settings
retry_delay: 960 
request_delay: 5
max_retries: 3 
request_timeout: 30

# Logging settings
log_level: 'INFO'
log_format: '%(asctime)s - %(levelname)s - %(message)s'